menu:
    首页: /
    归档: /archives/
    留言板: /guestbook.html
    # 简历: /resume.html
    OSC: https://git.oschina.net/yokoboy
    Rss: /atom.xml

favicon: /images/favicon.png
logo: /images/favicon.png

# Comment
# e.g disqus: seansun
# disqus:
duoshuo: yokoboy

# Analytics
# google-analytics:
ga: 

# Copyright Infomation
startyear: 2016

# Font CDN
#true : use google fonts api, not stable for chinese visitor sometimes, caused by force majeure factor
#false: use useso fonts api instead of google's, great response speed for chinese visitor
googlefonts: false
