menu:
    Home: /
    Blog: /blog
    Archive: /blog/archives/
    OSC: https://git.oschina.net/yokoboy
    Rss: /blog/atom.xml

favicon: /blog/images/favicon.png
logo: /blog/images/favicon.png

# Comment
# e.g disqus: seansun
# disqus:
duoshuo: yokoboy

# Analytics
# google-analytics:
ga: 

# Copyright Infomation
startyear: 2016

# Font CDN
#true : use google fonts api, not stable for chinese visitor sometimes, caused by force majeure factor
#false: use useso fonts api instead of google's, great response speed for chinese visitor
googlefonts: false
